/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrityHubRouteImport } from './routes/integrity-hub'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisputesIdRouteImport } from './routes/disputes.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityHubRoute = IntegrityHubRouteImport.update({
  id: '/integrity-hub',
  path: '/integrity-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIdRoute = DisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/integrity-hub'
    | '/login'
    | '/settings'
    | '/disputes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/integrity-hub'
    | '/login'
    | '/settings'
    | '/disputes/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/integrity-hub'
    | '/login'
    | '/settings'
    | '/disputes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IntegrityHubRoute: typeof IntegrityHubRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  DisputesIdRoute: typeof DisputesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity-hub': {
      id: '/integrity-hub'
      path: '/integrity-hub'
      fullPath: '/integrity-hub'
      preLoaderRoute: typeof IntegrityHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$id': {
      id: '/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof DisputesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IntegrityHubRoute: IntegrityHubRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  DisputesIdRoute: DisputesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
