/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IntegrityHubRouteImport } from './routes/integrity-hub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisputesIdRouteImport } from './routes/disputes.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityHubRoute = IntegrityHubRouteImport.update({
  id: '/integrity-hub',
  path: '/integrity-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesIdRoute = DisputesIdRouteImport.update({
  id: '/disputes/$id',
  path: '/disputes/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrity-hub': typeof IntegrityHubRoute
  '/settings': typeof SettingsRoute
  '/disputes/$id': typeof DisputesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/integrity-hub' | '/settings' | '/disputes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/integrity-hub' | '/settings' | '/disputes/$id'
  id: '__root__' | '/' | '/integrity-hub' | '/settings' | '/disputes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrityHubRoute: typeof IntegrityHubRoute
  SettingsRoute: typeof SettingsRoute
  DisputesIdRoute: typeof DisputesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity-hub': {
      id: '/integrity-hub'
      path: '/integrity-hub'
      fullPath: '/integrity-hub'
      preLoaderRoute: typeof IntegrityHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$id': {
      id: '/disputes/$id'
      path: '/disputes/$id'
      fullPath: '/disputes/$id'
      preLoaderRoute: typeof DisputesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrityHubRoute: IntegrityHubRoute,
  SettingsRoute: SettingsRoute,
  DisputesIdRoute: DisputesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
